### ISSUE TITLE
MYSQL image compatibility

### ISSUE THREAD

**Issue by rsahoo752055** [checkr/flagr#386] opened 2020-08-11 12:38 UTC
When we are trying to setup flagr image with mysql database (image version: latest/8/8.0/8.0.21), we are getting below error from mysql image container.
Error:: "INFO[0101] /go/src/github.com/checkr/flagr/pkg/handler/eval_cache_fetcher.go:147Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ASC,id ASC' at line 1
ERRO[0101] reload evaluation cache error                 err="Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ASC,id ASC' at line 1".

But when i am trying to setup flagr image with 5.7.31 or below mysql image version, flagr is working as excepted.

Please confirm mysql image compatibility version with flagr.

**Comment by brasilikum** [comment] 2020-08-12 21:07
Hey,
it seems like it worked as an accident.

Support for mysql is tracked here:
https://github.com/checkr/flagr/pull/331

Duplicate of #326

**Comment by zhouzhuojie** [comment] 2020-08-14 20:42
> Hey,
> it seems like it worked as an accident.
> 
> Support for mysql is tracked here:
> #331
> 
> Duplicate of #326

Oh, that's for MSSQL. I think this issue is related to MYSQL's compatibility. Will look into it soon.

**Closed** 2020-09-08 16:48 UTC
