### ISSUE TITLE
Added a port to work in the browser, would love a link to the project for everyone to use

### ISSUE THREAD

**Issue by DoryZi** [checkr/flagr#376] opened 2020-07-16 06:59 UTC
I've had issues with running this in the browser, so I created a port of the jsFlagr to work easily in the browser.
It's possible to also cdn host the output.

Have a look at:
https://github.com/CoreTeamIO/js-browser-flagr

Thanks, great project btw, just implemented it, super nice!

**Comment by zhouzhuojie** [comment] 2020-07-20 18:30
Thanks for the browser port! 

Duplicate of 
- https://github.com/checkr/jsflagr/issues/8
- https://github.com/checkr/flagr/issues/378

**Closed by zhouzhuojie** 2020-07-20 18:30 UTC
